---
title: "Convert TDRG_v5 to BigQuery"
author: "Carlos Resurreccion"
date: "2024-06-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(readxl)
library(writexl)
library(here)
```

```{r convert}
# Function to convert Excel files to CSV
convert_excel_to_csv <- function(folder_path) {
  # Get the absolute path to the folder
  abs_folder_path <- here(folder_path)
  
  # Get list of all Excel files in the folder
  excel_files <- list.files(path = abs_folder_path, pattern = "\\.xlsx$", full.names = TRUE)
  
  # Loop through each Excel file
  for (excel_file in excel_files) {
    # Read the Excel file with all columns as text to avoid type issues
    excel_data <- read_excel(excel_file, col_types = "text")
    
    # Create CSV file name by replacing .xlsx with .csv
    csv_file <- sub("\\.xlsx$", ".csv", excel_file)
    
    # Write the data to CSV file, leaving NA values as blanks
    write.csv(excel_data, file = csv_file, row.names = FALSE, na = "")
    
    # Print a message to indicate successful conversion
    cat("Converted:", excel_file, "to", csv_file, "\n")
  }
}

# Specify the folder containing Excel files relative to your project directory
folder_path <- "Excel"

# Call the function to convert Excel files to CSV
convert_excel_to_csv(folder_path)
```

