---
title: "DRG Cleaning"
author: "Carlos Resurreccion"
date: "2024-07-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Required Libraries

```{r library}
# library(tidyverse)
library(data.table)
library(here)
library(tictoc)
library(stringr)
library(stringi)
library(lubridate)
library(docstring)
library(profvis)
library(hash)
# library(foreach)
# library(doParallel)
# library(parallel)
library(future)
library(future.apply)
library(knitr)
```

## Set Parameters

### Year to Load

```{r year to load}
year_to_load <- "2018"
version <- "v2"
```

### Parameters

```{r parameters}
# Parameters
sample_size <- 25 * 1e3
seed <- 123

drop_cols <- c(paste0("ICDCODE",13:14),"ICCODED15",paste0("ICDCODE",16:170))

icd_cols <- paste0("clin_icd",1:12)
rvs_cols <- paste0("clin_rvs", 1:20)

to_read <- FALSE
to_sample <- TRUE
to_write <- TRUE
to_group <- TRUE
to_filter <- FALSE #unused
to_profvis <- FALSE
to_chunk <- FALSE
to_view_checks <- TRUE

na_values <- c('NONE', 'None', '-', '--', '---', 'N/A', 'n/a', 'nan', 'NAN')
na_like_strings <- c("", " ", "  ", "-", "none", "None", "NONE", "NA", "n/a", 
                     "N/A", "NaN", "'", "\t", "\n", "\r", "\f", "\v", "\u00A0",
                     "\u2000", "\u2001", "\u2002", "\u2003", "\u2004", "\u2005", 
                     "\u2006", "\u2007", "\u2008", "\u2009", "\u200A", "\u2028", 
                     "\u2029", "\u202F", "\u205F", "\u3000")

# File paths
path_to_raw_claims <- "git-ignored-files/raw-claims"
path_to_intermediate <- "git-ignored-files/intermediate-claims"
path_to_cache <- "data-cleaning/cache"
path_to_aux <- "git-ignored-files/aux-files"
path_to_excel <- "git-ignored-files/Excel"
path_to_cleaned_claims <- "git-ignored-files/cleaned-claims"
path_to_grouper_output <- "git-ignored-files/grouper-output"
path_to_chunks <- "git-ignored-files/chunked-samples"

# Here() let's you find files in your project directory

suffix <- paste0(ifelse(to_sample, "_sampled_", "_full_"), version)
sampled_claims <- here(
  path_to_raw_claims, 
  paste0("sampled_claims_extract_CLAIMS_", year_to_load, 
         suffix, paste0("_", sample_size), ".csv"))
full_claims <- here(
  path_to_raw_claims, 
  paste0("claims_extract_CLAIMS_", year_to_load, ".csv"))
intermediate_file <- here(
  path_to_intermediate, 
  paste0("intermediate_claims_", year_to_load, "_processed", suffix, ".csv"))
cleaned_claims_file <- here(
  path_to_cleaned_claims, 
  paste0("cleaned_claims_extract_CLAIMS_", year_to_load, suffix, ".csv"))
output_txt_file <- here(
  path_to_grouper_output, 
  paste0("DRG_Grouped", "_", year_to_load, suffix, ".txt"))
grouper_result_file <- here(
  path_to_grouper_output, 
  toupper(paste0("DRG_Grouped", "_", year_to_load, suffix, "Res.TXT")))
total_rows_file <- here(
  path_to_cache,
  paste0("total_rows_", year_to_load, ".rds")
)


# Seed for reproducibility
set.seed(seed)

options(future.globals.maxSize= 1024*1024^2)

global_seed <- seed #for parallelized operations
```

## Source Data Formats

```{r data formats and additional parameters}
source(here("data-cleaning", "data-formats.R"))
```

## Source Functions

```{r}
source(here("data-cleaning", "general-functions.R"))
source(here("data-cleaning", "icd-functions.R"))
source(here("data-cleaning", "rvs-functions.R"))
source(here("data-cleaning", "pdx-functions.R"))
source(here("data-cleaning", "grouper-functions.R"))
```

## Load Mapping Data

```{r load mapping data}
proc <- fread(here(path_to_excel, "proc.csv"))
proc[, CODE := as.character(CODE)]

rvs_icd9 <- fread(here(path_to_aux, "rvs_icd9cm.csv"), 
                  select = c("rvs", "icd9cm"))
rvs_icd9[, rvs := as.character(rvs)]
rvs_icd9[, icd9cm := as.character(icd9cm * 100)]
rvs_icd9 <- merge(rvs_icd9, proc[, .(CODE, DRGUSE)], 
                  by.x = "icd9cm", by.y = "CODE", all.x = TRUE)
rvs_icd9[, is_drg := !is.na(DRGUSE) & DRGUSE]
rvs_icd9 <- rvs_icd9[!is.na(rvs) & !is.na(icd9cm), -"DRGUSE"]

acr_rvs <- fread(here(path_to_aux, "acr_rvs.csv"))

# Read in the data.table
tdrg_icd10 <- fread(here(path_to_aux, "i10.csv"))

# Set the key if not already set
setkey(tdrg_icd10, "CODE")

# Subset and assign the result to acc_pdx
acc_pdx <- tdrg_icd10[ACCPDX == "Y", CODE]

# Optional: if CODEs are not unique in tdrg_icd10
acc_pdx <- unique(acc_pdx)
```

## Read Data

### Reading Data

```{r reading, warning = FALSE}
if (to_read) {
  if (to_view_checks) {
    print("Reading the entire file...")
  }
  dt <- read_entire_file(drop_cols)
  
  if (to_sample) {
    if (file.exists(sampled_claims)) {
      if (to_view_checks) {
        print("Sampled file exists. Reading the sampled file...")
      }
      dt <- read_sampled_file()
      # Check if the number of rows matches sample_size
      if (nrow(dt) != sample_size) {
        if (to_view_checks) {
          print(paste("Sampled file does not match sample size. Expected:", 
                    sample_size, "Found:", nrow(dt), "Re-sampling..."))
        }
        dt <- read_entire_file(drop_cols)
        dt <- sample_data(dt)
        if (to_write) {
          if (to_view_checks) {
            print(paste("to_write is TRUE. Writing the new sample data to file:", 
                      sampled_claims))
          }
          fwrite(dt, sampled_claims)
        } else {
          if (to_view_checks) {
            print("to_write is FALSE. Not writing the sample data to file.")
          }
        }
      } else {
        if (to_view_checks) {
          print("Sampled file matches sample size.")
        }
      }
    } else {
      if (to_view_checks) {
        print("Sampled file does not exist. Creating new sample...")
      }
      dt <- sample_data(dt)
      if (to_write) {
        if (to_view_checks) {
          print(paste("to_write is TRUE. Writing the new sample data to file:", 
                    sampled_claims))
        }
        fwrite(dt, sampled_claims)
      } else {
        if (to_view_checks) {
          print("to_write is FALSE. Not writing the sample data to file.")
        }
      }
    }
  }
} else {
  if (to_sample) {
    if (file.exists(sampled_claims)) {
      if (to_view_checks) {
        print("Sampled file exists. Reading the sampled file...")
      }
      dt <- read_sampled_file()
      # Check if the number of rows matches sample_size
      if (nrow(dt) != sample_size) {
        if (to_view_checks) {
          print(paste("Sampled file does not match sample size. Expected:", 
                    sample_size, "Found:", nrow(dt), "Re-sampling..."))
        }
        dt <- read_entire_file(drop_cols)
        dt <- sample_data(dt)
        if (to_write) {
          if (to_view_checks) {
            print(paste("to_write is TRUE. Writing the new sample data to file:", 
                      sampled_claims))
          }
          fwrite(dt, sampled_claims)
        } else {
          if (to_view_checks) {
            print("to_write is FALSE. Not writing the sample data to file.")
          }
        }
      } else {
        if (to_view_checks) {
          print("Sampled file matches sample size.")
        }
      }
    } else {
      if (to_view_checks) {
        print("Sampled file does not exist.")
        print("Reading entire file and creating new sample...")
      }
      dt <- read_entire_file(drop_cols)
      dt <- sample_data(dt)
      if (to_write) {
        if (to_view_checks) {
          print(paste("to_write is TRUE. Writing the new sample data to file:", 
                    sampled_claims))
        }
        fwrite(dt, sampled_claims)
      } else {
        if (to_view_checks) {
          print("to_write is FALSE. Not writing the sample data to file.")
        }
      }
    }
  } else {
    if (!file.exists(intermediate_file)) {
      stop("Cannot proceed: to_read is FALSE and to_sample is FALSE. 
           At least one must be TRUE.")
    } else {
      if (to_view_checks) {
        print("Using existing intermediate file.")
      }
    }
  }
}

if (file.exists(total_rows_file)) {
  total_rows <- readRDS(total_rows_file)
} else {
  total_rows <- fread(full_claims, select = 1L, header = TRUE)[, .N]
  saveRDS(total_rows, file = total_rows_file)
}
```

## Data Processing

### Data Cleaning

```{r define main cleaning and chunking functions}
clean_data <- function(dt) {
  original_col_order <- colnames(dt) # TODO can delete
  
  # Add year column
  dt[, SRC_YR := as.integer(year_to_load)] # unwrapped/deprecated the old function
  # Rename columns
  setnames(dt, old = old_colnames, new = new_colnames)  # unwrapped/deprecated the old function
  # Check: Print new colnames
  if (to_view_checks) {
    print(colnames(dt))
    print("Successfully renamed columns; All expected columns exist")
  }
  # Collapse columns clin_icd1 to clin_icd12 into clin_icd
  # dt <- process_and_collapse_columns(dt, icd_cols, "clin_icd") # unwrapped/deprecated the old function
  dt[, clin_icd := collapse_columns(mget(paste0("clin_icd", 1:12), 
                                         envir = as.environment(dt)), 
                                    na_like_strings)]
  dt[, paste0("clin_icd", 1:12) := NULL]
   
  # Collapse columns clin_rvs1 to clin_rvs20 into clin_rvs
  # dt <- process_and_collapse_columns(dt, rvs_cols, "clin_rvs") # unwrapped/deprecated the old function
  dt[, clin_rvs := collapse_columns(mget(paste0("clin_rvs", 1:20), 
                                         envir = as.environment(dt)), 
                                    na_like_strings)]
  dt[, paste0("clin_rvs", 1:20) := NULL]
  
  # Remove lumped ICD codes from clin_icd
  # dt <- remove_lumped_icd_codes(dt, "clin_icd")  # unwrapped/deprecated the old function
  dt[, clin_icd := remove_lumped_icd_codes(dt$clin_icd)]

  # Turn clin_icd and clin_rvs into lists
  dt[, clin_icd := split_to_vector(clin_icd)]
  dt[, clin_rvs := split_to_vector(clin_rvs)]
  
  # Clean and unlump clin_c1 and clin_c2
  # dt <- clean_columns_in_dt(dt, c("clin_c1", "clin_c2")) # unwrapped/deprecated function
  
  # Clean columns (new):
  dt[, clin_c1_orig := clin_c1]
  dt[, clin_c1 := clean_column(dt$clin_c1, na_like_strings)]
  clin_c1_cleaning_comparison <- dt[clin_c1 != clin_c1_orig, .(clin_c1_orig, clin_c1)]
  if (to_view_checks) {
    View(head(clin_c1_cleaning_comparison)) # Check: Print head of changes
  }
  dt[, clin_c1_orig := NULL]
  
  dt[, clin_c2_orig := clin_c2]
  dt[, clin_c2 := clean_column(dt$clin_c2, na_like_strings)]
  clin_c2_cleaning_comparison <- dt[clin_c2 != clin_c2_orig, .(clin_c2_orig, clin_c2)]
  if (to_view_checks) {
    View(head(clin_c2_cleaning_comparison)) # Check: Print head of changes
  }
  dt[, clin_c2_orig := NULL]
  
  dt[, clin_c1 := remove_lumped_icd_codes(dt$clin_c1)]
  dt[, clin_c2 := remove_lumped_icd_codes(dt$clin_c2)]
  
  dt[, clin_c1 := split_to_vector(clin_c1)]
  # dt <- process_icd10_codes(dt, "clin_c1")  # unwrapped/deprecated function
  clin_c1_result <- transfer_extra_icd10s_to_clin_icd(dt$clin_icd, dt$clin_c1)
  dt[, clin_icd := clin_c1_result$clin_icd]
  dt[, clin_c1 := clin_c1_result$col_first]
  
  dt[, clin_c2 := split_to_vector(clin_c2)]
  # dt <- process_icd10_codes(dt, "clin_c2")  # unwrapped/deprecated function
  clin_c2_result <- transfer_extra_icd10s_to_clin_icd(dt$clin_icd, dt$clin_c2)
  dt[, clin_icd := clin_c2_result$clin_icd]
  dt[, clin_c2 := clin_c2_result$col_first]
  
  # dt <- append_and_remove_rvs(dt, "clin_c1") # unwrapped/deprecated function
  # dt <- append_and_remove_rvs(dt, "clin_c2") # unwrapped/deprecated function
  
  clin_c1_rvs_results <- append_and_remove_rvs(dt$clin_rvs, dt$clin_c1)
  dt[, clin_rvs := clin_c1_rvs_results$clin_rvs]
  dt[, clin_c1 := clin_c1_rvs_results$col]
  
  clin_c2_rvs_results <- append_and_remove_rvs(dt$clin_rvs, dt$clin_c2)
  dt[, clin_rvs := clin_c2_rvs_results$clin_rvs]
  dt[, clin_c2 := clin_c2_rvs_results$col]
  
  dt[, clin_rvs := lapply(clin_rvs, unique)]
  dedup_result <- deduplicate_and_ensure_unique_icd_codes(dt$clin_c1, 
                                                          dt$clin_c2, 
                                                          dt$clin_icd)
  dt[, clin_c1 := dedup_result$clin_c1]
  dt[, clin_c2 := dedup_result$clin_c2]
  dt[, clin_icd := dedup_result$clin_icd]
  
  # Replace empty strings in character and factor columns with NA
  dt <- replace_empty_with_na(dt, to_view_checks)
  
  dt[, pat_type := remap_patient_type(pat_type)]
  if (to_view_checks) {
    print("Patient Types:")
    print(unique(dt$pat_type))
  }
  
  dt[, pat_memcat_parent := remap_memcat_parent_desc(pat_memcat_parent)]
  if (to_view_checks) {
    print("Memcat Parent Types:")
    print(unique(dt$pat_memcat_parent))
  }
  
  dt[, pat_memcat_child := remap_memcat_child_desc(pat_memcat_child)]
  if (to_view_checks) {
    print("Memcat Child Types:")
    print(unique(dt$pat_memcat_child))
  }
  
  dt[, clin_discharge := remap_disposition(clin_discharge)]
  if (to_view_checks) {
    print("Discharge Types:")
    print(unique(dt$clin_discharge))
  }

  return(dt)
}


process_chunk <- function(chunk) {
  #' @title Process Data Chunk
  #' @description Processes a data chunk by cleaning, mapping codes, replacing 
  #' empty values, and finding the primary diagnosis (PDX).
  #' @param chunk A data.table chunk to process.
  #' @return The processed data.table chunk.
  #'
  #' @details
  #' This function performs the following operations on the data chunk:
  #' - Suppresses console output to keep the environment clean.
  #' - Cleans the data using the clean_data function.
  #' - Maps RVS and ICD-10 codes.
  #' - Replaces empty strings with NA values.
  #' - Finds the primary diagnosis (PDX) using the apply_find_pdx function.
  #'
  #' @examples
  #' library(data.table)
  #' chunk <- data.table(...) # Load your data chunk
  #' processed_chunk <- process_chunk(chunk)
  #' print(processed_chunk) # Should print the processed data chunk
  
  # Suppress output
  if (to_view_checks) {
    print("Viewing checks")
  } else {
    sink(tempfile())
    on.exit(sink(), add = TRUE)
  }
  
  # Clean data
  chunk <- clean_data(chunk)
  
  # Map codes
  chunk <- map_rvs_icd9(chunk, rvs_icd9)
  chunk <- implement_icd10_mapping(chunk)
  
  # Replace empty strings with NA values
  chunk <- replace_empty_with_na(chunk)
  
  # Find PDX
  chunk <- apply_find_pdx(chunk, acc_pdx)
  
  return(chunk)
}
```

#### Not chunking

```{r logic if not chunking}
if (!to_chunk){
  tic("Total execution time:")
  if (to_profvis) {
    profvis({
      dt <- clean_data(dt)
    })
  } else {
    dt <- clean_data(dt)
  }
} 
```

#### Chunking

```{r logic if chunking}
if (to_chunk){
  tic("Total execution time:")
  if (to_profvis) {
    profvis({
      num_cores <- max(1, availableCores() - 1)
      chunk_size <- ceiling(nrow(dt) / num_cores)
      chunks <- split(dt, rep(1:num_cores, each = chunk_size, 
                              length.out = nrow(dt)))
      # Plan for parallel processing
      plan(multisession, workers = num_cores)
      # Process each chunk in parallel
      processed_chunks <- future_lapply(chunks, process_chunk, 
                                        future.seed = global_seed)
      # Combine processed chunks
      dt <- rbindlist(processed_chunks)
      dt <- replace_empty_with_na(dt, to_view_checks)
    })
  } else {
      num_cores <- max(1, availableCores() - 1)
      chunk_size <- ceiling(nrow(dt) / num_cores)
      chunks <- split(dt, rep(1:num_cores, each = chunk_size, 
                              length.out = nrow(dt)))
      # Plan for parallel processing
      plan(multisession, workers = num_cores)
      # Process each chunk in parallel
      processed_chunks <- future_lapply(chunks, process_chunk, 
                                        future.seed = global_seed)
      # Combine processed chunks
      dt <- rbindlist(processed_chunks)
      dt <- replace_empty_with_na(dt, to_view_checks)
  }
}
```

### Map codes and Find PDx (if not chunking)

#### Map Codes

```{r map codes}
#Map RVS codes
if (!to_chunk){
  if (to_profvis) {
    profvis({
      dt <- map_rvs_icd9(dt, rvs_icd9)
      dt <- implement_icd10_mapping(dt)
      # Replace empty strings in character and factor columns with NA
      dt <- replace_empty_with_na(dt, to_view_checks)
    })
  } else {
      dt <- map_rvs_icd9(dt, rvs_icd9)
      dt <- implement_icd10_mapping(dt)
      # Replace empty strings in character and factor columns with NA
      dt <- replace_empty_with_na(dt, to_view_checks)
  }
}
```

#### Find PDx

```{r find pdx}
#Map RVS codes
if (!to_chunk) {
  if (to_profvis) {
    profvis({
      dt <- apply_find_pdx(dt, acc_pdx)
    })
  } else {
      dt <- apply_find_pdx(dt, acc_pdx)
  }
}
```

```{r write}
if (to_write) {
  fwrite(dt, here(path_to_intermediate, paste0("output_", year_to_load, 
                                               suffix, ".csv")))
}
```

## Export

### Export for Batch Grouper

```{r group}
if (to_group) {
  if (to_profvis) {
    profvis({
      export_for_batch_grouper(dt, year_to_load, output_txt_file)
      for_batch_grouping <- fread(output_txt_file, 
                                  sep = "|", na.strings = "--")
      batch_grouping_result <- fread(grouper_result_file, 
                                     sep = "|", na.strings = "--")
    })
  } else {
      export_for_batch_grouper(dt, year_to_load, output_txt_file)
      for_batch_grouping <- fread(output_txt_file, 
                                  sep = "|", na.strings = "--")
      batch_grouping_result <- fread(grouper_result_file, 
                                     sep = "|", na.strings = "--")
  }
}
```

## Runtime Estimation

### Stop Timer 

```{r stop timer}
# Stop the timer and capture total time
toc_data <- toc(log = TRUE)
total_time <- toc_data$toc - toc_data$tic
```
### Calculate Speed

```{r calculate speed}
# Calculate time spent per cell and per row
total_rows_dt <- nrow(dt)
total_cells <- nrow(dt) * ncol(dt)

time_per_cell <- total_time / total_cells
time_per_row <- total_time / total_rows_dt
time_estimate_total_rows <- time_per_row * total_rows

# Format the row numbers
formatted_total_rows_dt <- format_large_numbers(total_rows_dt)
formatted_total_rows <- format_large_numbers(total_rows)

# Print the results with aligned decimal points and formatted row numbers
cat(sprintf("Time spent (total) for %2s rows:  %1.2f sec  (actual)\n", 
            formatted_total_rows_dt, total_time))
cat(sprintf("Time spent (t/row) for %2s rows:  %1.2f msec (actual)\n", 
            formatted_total_rows_dt, time_per_row * 1000))
cat(sprintf("Time spent (total) for  %2s rows: %2.2f min  (estimate)\n", 
            formatted_total_rows, time_estimate_total_rows / 60))
```
