---
title: "DRG Cleaning"
author: "Carlos Resurreccion"
date: "2024-07-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Required Libraries

```{r library}
library(data.table)
library(here)
library(tictoc)
library(stringr)
library(stringi)
library(lubridate)
library(docstring)
```

## Set Parameters

### Year to Load

```{r year to load}
year_to_load <- "2018"
```

### Parameters

```{r parameters}
# Parameters
sample_size <- 1 * 1e3
chunk_size <- 1e6

drop_cols <- c(paste0("ICDCODE",13:14),"ICCODED15",paste0("ICDCODE",16:170))

to_read <- FALSE
to_sample <- TRUE
to_write <- TRUE
to_chunk <- FALSE
to_group <- TRUE
to_filter <- TRUE

na_values <- c('NONE', 'None', '-', '--', '---', 'N/A', 'n/a', 'nan', 'NAN')
na_like_strings <- c("", " ", "  ", "-", "none", "None", "NONE", "NA", "n/a", 
                     "N/A", "NaN", "'", "\t", "\n", "\r", "\f", "\v", "\u00A0",
                     "\u2000", "\u2001", "\u2002", "\u2003", "\u2004", "\u2005", 
                     "\u2006", "\u2007", "\u2008", "\u2009", "\u200A", "\u2028", 
                     "\u2029", "\u202F", "\u205F", "\u3000")

# File paths
path_to_raw_claims <- "git-ignored-files/raw_claims"
path_to_intermediate <- "git-ignored-files/intermediate_claims"
path_to_cache <- "data-cleaning/cache"
path_to_aux <- "git-ignored-files/aux_files"
path_to_excel <- "git-ignored-files/Excel"
path_to_cleaned_claims <- "git-ignored-files/cleaned_claims"
path_to_grouper_output <- "git-ignored-files/grouper_output"

suffix <- ifelse(to_sample, "_sampled", "_full")
chunk_droppable_cols_file <- here(
  path_to_cache, 
  paste0("chunk_droppable_cols_", year_to_load, suffix, ".rds"))
header_file <- here(
  path_to_cache, 
  paste0("header_", year_to_load, suffix, ".rds"))
total_rows_file <- here(
  path_to_cache, 
  paste0("total_rows_", year_to_load, suffix, ".rds"))
sampled_claims <- here(
  path_to_raw_claims, 
  paste0("sampled_claims_extract_CLAIMS_", year_to_load, ".csv"))
full_claims <- here(
  path_to_raw_claims, 
  paste0("claims_extract_CLAIMS_", year_to_load, ".csv"))
intermediate_file <- here(
  path_to_intermediate, 
  paste0("intermediate_claims_", year_to_load, "_processed.csv"))
cleaned_claims_file <- here(
  path_to_cleaned_claims, 
  paste0("cleaned_claims_extract_CLAIMS_", year_to_load, suffix, ".csv"))
output_txt_file <- here(
  path_to_grouper_output, 
  paste0("DRG_Grouped", suffix, "_", year_to_load, ".txt"))
grouper_result_file <- here(
  path_to_grouper_output, 
  toupper(paste0("DRG_Grouped", suffix, "_", year_to_load, "Res.TXT")))

# Seed for reproducibility
set.seed(123)
```

## Source Data Formats

```{r data formats and additional parameters}
source(here("data-cleaning", "r_scripts", "data-formats.R"))
```

## Source Functions

```{r}
source(here("data-cleaning", "r_scripts", "functions.R"))
```

## Load Mapping Data

```{r load mapping data}
proc <- fread(here(path_to_excel, "proc.csv"))
proc[, CODE := as.character(CODE)]

rvs_icd9 <- fread(here(path_to_aux, "rvs_icd9cm.csv"), select = c("rvs", "icd9cm"))
rvs_icd9[, rvs := as.character(rvs)]
rvs_icd9[, icd9cm := as.character(icd9cm * 100)]
rvs_icd9 <- merge(rvs_icd9, proc[, .(CODE, DRGUSE)], by.x = "icd9cm", by.y = "CODE", all.x = TRUE)
rvs_icd9[, is_drg := !is.na(DRGUSE) & DRGUSE]
rvs_icd9 <- rvs_icd9[!is.na(rvs) & !is.na(icd9cm), -"DRGUSE"]

acr_rvs <- fread(here(path_to_aux, "acr_rvs.csv"))

# Read in the data.table
tdrg_icd10 <- fread(here(path_to_aux, "i10.csv"))

# Set the key if not already set
setkey(tdrg_icd10, "CODE")

# Subset and assign the result to acc_pdx
acc_pdx <- tdrg_icd10[ACCPDX == "Y", CODE]

# Optional: If you want to ensure uniqueness (if CODEs are not unique in tdrg_icd10)
acc_pdx <- unique(acc_pdx)
```

## Read Data

### Reading Data

```{r reading}
if (to_read) {
  dt <- read_entire_file(drop_cols)
  
  if (to_sample) {
    if (file.exists(sampled_claims)) {
      dt <- read_sampled_file()
      # Check if the number of rows matches sample_size
      if (nrow(dt) != sample_size) {
        dt <- read_entire_file(drop_cols)
        dt <- sample_data(dt)
        if (to_write) {
          write_data(dt, sampled_claims)
        }
      }
    } else {
      dt <- sample_data(dt)
      if (to_write) {
        write_data(dt, sampled_claims)
      }
    }
  }
} else {
  if (to_sample) {
    if (file.exists(sampled_claims)) {
      dt <- read_sampled_file()
      # Check if the number of rows matches sample_size
      if (nrow(dt) != sample_size) {
        dt <- read_entire_file(drop_cols)
        dt <- sample_data(dt)
        if (to_write) {
          write_data(dt, sampled_claims)
        }
      }
    } else {
      dt <- read_entire_file(drop_cols)
      dt <- sample_data(dt)
      if (to_write) {
        write_data(dt, sampled_claims)
      }
    }
  } else if (to_chunk) {
    if (!file.exists(chunk_droppable_cols_file) || !file.exists(header_file) || !file.exists(total_rows_file)) {
      process_chunks()
    } else {
      chunk_droppable_cols <- readRDS(chunk_droppable_cols_file)
      header <- readRDS(header_file)
      total_rows <- readRDS(total_rows_file)
    }
  } else {
    if (!file.exists(intermediate_file)) {
      stop("Cannot proceed: to_read is FALSE, to_sample is FALSE, and to_chunk is FALSE. At least one must be TRUE.")
    }
  }
}
```

### Identify Droppable Columns

```{r identify droppable columns}
if (to_read || (to_sample && !file.exists(sampled_claims))) {
  chunk_number <- 1
  chunk_droppable_cols <- list()
  header <- names(dt)
  total_rows <- nrow(dt)

  tic("Processing header row")
  cols_to_keep <- setdiff(seq_along(header), drop_cols)
  toc()

  tic("Identifying droppable columns")
  droppable_cols <- sapply(dt, function(col) all(is.na(col) || col %in% na_like_strings))
  droppable_cols <- which(droppable_cols)
  chunk_droppable_cols[[paste0(year_to_load, "_whole")]] <- droppable_cols
  toc()

  saveRDS(chunk_droppable_cols, chunk_droppable_cols_file)
  saveRDS(header, header_file)
  saveRDS(total_rows, total_rows_file)
}
```

## Process Data in Chunks

### Process

```{r process data in chunks}
if (to_sample == FALSE && to_chunk == TRUE) {
  tic("Processing data in chunks")
  
  header <- fread(full_claims, nrows = 1, header = TRUE)
  total_rows <- fread(full_claims, select = 1L, header = TRUE)[, .N]
  cols_to_keep <- setdiff(seq_along(header), drop_cols)
  
  chunk_number <- 1
  repeat {
    skip_rows <- (chunk_number - 1) * chunk_size + 1
    if (skip_rows > total_rows) break
    
    droppable_cols <- process_chunk(chunk_number, skip_rows, cols_to_keep, total_rows, rvs_icd9)
    if (is.null(droppable_cols)) break
    
    chunk_number <- chunk_number + 1
  }
  
  toc()
}
```

### Merge Intermediate Files

```{r merge intermediate files}
if (to_sample == FALSE && to_chunk == TRUE && to_write == TRUE) {
  tic("Merging intermediate files")
  
  intermediate_files <- list.files(path_to_intermediate, pattern = "intermediate_chunk_.*\\.csv", full.names = TRUE)
  dt_list <- lapply(intermediate_files, fread)
  dt <- rbindlist(dt_list)
  
  fwrite(dt, intermediate_file)
  
  toc()
}
```

## Process Data if Not Chunking

### Process Data

```{r process data if not chunking}
if (to_chunk == FALSE && exists("dt")) {
  tic("Process data if not chunking")
  dt <- process_data(dt, year_to_load, rvs_icd9)
  
  if (to_write) {
    fwrite(dt, intermediate_file)
  }
  toc()
}
```

### Process for PDx

```{r}
tic("Process data for likely PDx")
dt <- process_data_for_pdx(dt, rvs_icd9, path_to_cache, year_to_load)

# Check the results
dt_select <- dt[, .(PSEUDO_CLAIMSERIES, pdx, pdx_code, PRIMARY_ILLNESS, SECONDARY_ILLNESS, ICD_CODES, RVS_CODES, clin_c1, clin_c2, icd_list)]
toc()
```

## Save Cleaned Data File

```{r}
tic("Save cleaned file")
if (to_write) {
  saveRDS(dt, here(path_to_cache, paste0("claims_prepdx_", year_to_load, ".rds")))
}
toc()
```

## Export for Batch Grouper Software

```{r}
tic("Export for batch grouper")
if (to_group) {
  if (to_filter) {
    # Filter out rows where pdx is NA
    dt <- dt[!is.na(dt$pdx), ]
  }
  export_for_batch_grouper(dt, year_to_load, output_txt_file)
}

for_batch_grouping <- fread(output_txt_file, sep = "|", na.strings = "--")
batch_grouping_result <- fread(grouper_result_file, sep = "|", na.strings = "--")
toc()
```